### ISSUE TITLE
ModelWriter as a Next Generation Requirements Engineering Tool: ModelWriter should be equipped with Requirements Engineering features.

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Requirements#53]
The text below is an excerpt from the FPP (Section 2.2.2.4):

> A requirements engineering tool such as the dominant Rationale DOORS is basically comparable to a database management system. ModelWriter equipped with the envisioned Requirements Engineering features will be far superior to such “advanced” tool by providing the following innovative features (list far from being exhaustive!):
> - The most natural (i.e. **word processor-like** rather than database-like) interface for users, resulting in quantum leap of efficiency in requirements capture. Indeed, users naturally express their requirements in a written way (incl. graphics and nice layout), not in a database-oriented manner. Moreover, requirements documents generated from the database by today’s tools are easily recognizable by the questionable readability, which is a problem that is simply avoided by the ModelWriter’s approach.
> - Intelligent features for checking the readability (lack of ambiguity), completeness and consistency of the proposed requirements, e.g. by using ORM verbalization mechanism and model checkers (to be developed by KUL2, see UC-BE-01): computer-assisted Quality Reviews.
> - Intelligent features for further manipulating the requirements, e.g. for creating or verifying traceability matrices between 2 sets of requirements (=computer-assisted traceability matrices), with e.g. applications for verifying compliance to standards.

**Comment by annemonceaux** [comment]
This requirement should be reviewed since KUL2 is finally not partner in ModelWriter.
Was there any work so far on ORM?
