### ISSUE TITLE
The system shall provide a reconciliation component to deal with hard changes of texts or concepts of a mapping

### ISSUE THREAD

**Issue by mrostren** [ModelWriter/Requirements#58]
This software requirement is related to https://github.com/ModelWriter/Requirements/issues/47 and to https://github.com/ModelWriter/Requirements/issues/57

Depending on the kind of changes (to define later) the reconciliation can or can not be done. In the last case, the decision belongs to the user.

**Comment by annemonceaux** [comment]
doesn't the decision belong to the user in all cases?

**Comment by ferhaterata** [comment]
Is this requirement still valid? Because It was closed today.
